name: upload_conda

on:
  release:
    types: ['released', 'prereleased']
  workflow_dispatch: # used to trigger manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest, macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: recipe/build_env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          conda-remove-defaults: "true"
      - name: Enforce .tar.bz2 packages
        # Temporary work-arounds while the action uibcdf/action-build-and-upload-conda-packages gets updated:
        # We create a `~/.condarc` file with the correct options to enforce the use of `.tar.bz2` packages
        # and we set the channels to be used by conda build
        shell: bash
        run: |
          cat > ~/.condarc << EOF
          conda-build:
            pkg_format: .tar.bz2
          channels:
            - conda-forge
            - nodefaults
          
          EOF
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.4.0
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        with:
          meta_yaml_dir: recipe
          python-version: ${{ matrix.python-version }}
          user: rykerfish
          overwrite: true
          upload: true
          label: main
          token: ${{ secrets.ANACONDA_TOKEN }}
